# Generated by Django 4.1.7 on 2023-03-19 09:44

import apps.profiles.models
import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="created_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="facebook",
            new_name="fullname",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="updated_date",
            new_name="updated",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="github",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gitlab",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="lastname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="medium",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="orcid",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="photo_full",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skype",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stackoverflow",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="task_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="youtube",
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "full",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.profiles.models.photo_path
                    ),
                ),
                (
                    "cropped",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.profiles.models.photo_path
                    ),
                ),
                ("crop_x", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("crop_y", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("crop_width", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "crop_height",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "profile",
                    auto_prefetch.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
