# Generated by Django 4.1.7 on 2023-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="active_photo",
            new_name="photo_active",
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
