# Generated by Django 4.1.7 on 2023-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_active",
            field=models.BooleanField(default=False, verbose_name="Birth date"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location_active",
            field=models.BooleanField(default=False, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_active",
            field=models.BooleanField(default=False, verbose_name="Website"),
        ),
    ]
