# Generated by Django 4.1.7 on 2023-03-26 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_setting"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Setting",
            new_name="ProfileSetting",
        ),
    ]
