# Generated by Django 4.1.7 on 2023-06-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_active_photo_profile_photo_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labelsettings",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="achievement_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="achievement_label",
            field=models.CharField(default="Achievements", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_label",
            field=models.CharField(default="Education", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience_label",
            field=models.CharField(default="Work experience", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="jobtitle_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="language_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="language_label",
            field=models.CharField(default="Languages", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="project_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="project_label",
            field=models.CharField(default="Projects", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="publication_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="publication_label",
            field=models.CharField(default="Publications", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="skill_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skill_label",
            field=models.CharField(default="Skills", max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description_label",
            field=models.CharField(default="About me", max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_label",
            field=models.CharField(default="Website label", max_length=32),
        ),
        migrations.DeleteModel(
            name="ActivationSettings",
        ),
        migrations.DeleteModel(
            name="LabelSettings",
        ),
    ]
