# Generated by Django 4.1.7 on 2023-03-19 14:23
import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_created_date_profile_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField(default=50)),
            ],
            options={
                "ordering": ("-level",),
                "abstract": False,
                "default_related_name": "skills",
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="education",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="honor",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="language",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="patent",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="project",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="template",
        ),
        migrations.RemoveField(
            model_name="volunteering",
            name="profile",
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="name",
        ),
        migrations.AddField(
            model_name="skill",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="profile",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="Honor",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Patent",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
        migrations.DeleteModel(
            name="Volunteering",
        ),
        migrations.AddField(
            model_name="skillitem",
            name="skill",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.skill"
            ),
        ),
    ]
