# Generated by Django 4.1.7 on 2023-06-10 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_birth_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ("order",),
                "verbose_name_plural": "Education",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ("order",),
                "verbose_name_plural": "Experience",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
    ]
