# Generated by Django 4.1.7 on 2023-03-19 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_skillitem_remove_course_profile_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="SkillField",
        ),
        migrations.AlterModelOptions(
            name="skillfield",
            options={
                "base_manager_name": "prefetch_manager",
                "default_related_name": "skillfield",
            },
        ),
    ]
