# Generated by Django 4.1.7 on 2023-06-05 20:01

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_labelsettings_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="crop_height",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="crop_width",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="crop_x",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="crop_y",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="cropped_photo",
            field=models.ImageField(
                null=True, upload_to=apps.profiles.models.get_upload_path
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_photo",
            field=models.ImageField(
                null=True, upload_to=apps.profiles.models.get_upload_path
            ),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
