# Generated by Django 4.1.7 on 2023-03-24 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_rename_skillset_skill_alter_birth_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skillitem",
            old_name="skill_set",
            new_name="skill",
        ),
    ]
