# Generated by Django 4.1.7 on 2023-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_achievement_options_alter_education_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
