# Generated by Django 4.1.7 on 2023-03-26 19:57

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_rename_setting_profilesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilesetting",
            name="profile",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setting",
                to="profiles.profile",
            ),
        ),
    ]
