# Generated by Django 4.1.7 on 2023-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_about_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="jobtitle",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
