# Generated by Django 4.1.7 on 2023-03-19 16:14
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_rename_skill_skillfield_alter_skillfield_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkillField",
            new_name="Skill",
        ),
        migrations.AlterModelOptions(
            name="skillitem",
            options={"base_manager_name": "prefetch_manager", "ordering": ("-level",)},
        ),
    ]
