# Generated by Django 4.1.7 on 2023-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_profile_crop_height_profile_crop_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="website_active",
            field=models.BooleanField(default=True, verbose_name="Website"),
        ),
    ]
