# Generated by Django 4.1.7 on 2023-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profilesetting_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labelsetting",
            name="profile",
        ),
        migrations.AddField(
            model_name="profilesetting",
            name="active_description",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilesetting",
            name="label_description",
            field=models.CharField(default="About me", max_length=32),
        ),
        migrations.DeleteModel(
            name="ActiveSetting",
        ),
        migrations.DeleteModel(
            name="LabelSetting",
        ),
    ]
