# Generated by Django 4.1.7 on 2023-03-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_rename_skill_set_skillitem_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
