# Generated by Django 4.1.7 on 2023-04-02 13:10
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_skill_options_remove_skill_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skillitem",
            old_name="skill",
            new_name="set",
        ),
    ]
