# Generated by Django 4.1.7 on 2023-06-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_profile_website_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_label",
            field=models.CharField(default="Birth date", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_label",
            field=models.CharField(default="Email address", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="fullname_label",
            field=models.CharField(default="Full name", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="jobtitle_label",
            field=models.CharField(default="Job Title", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_label",
            field=models.CharField(default="Location", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_label",
            field=models.CharField(default="Phone number", max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_label",
            field=models.CharField(default="Website", max_length=32),
        ),
    ]
