# Generated by Django 4.1.7 on 2023-04-02 13:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_rename_skill_skillitem_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillitem",
            name="profile",
        ),
    ]
