# Generated by Django 4.1.7 on 2023-03-19 16:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_rename_skillfield_skill_alter_skillitem_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="SkillSet",
        ),
        migrations.AlterModelOptions(
            name="skillset",
            options={
                "base_manager_name": "prefetch_manager",
                "default_related_name": "skill_set",
            },
        ),
    ]
