# Generated by Django 4.1.7 on 2023-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_profile_birth_label_profile_email_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="jobtitle_label",
            field=models.CharField(default="Job title", max_length=32),
        ),
    ]
