# Generated by Django 4.1.7 on 2023-03-19 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_rename_skill_skillset_alter_skillset_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillitem",
            options={
                "base_manager_name": "prefetch_manager",
                "default_related_name": "items",
                "ordering": ("-level",),
            },
        ),
        migrations.RenameField(
            model_name="skillitem",
            old_name="skill",
            new_name="skill_set",
        ),
    ]
