# Generated by Django 4.1.7 on 2023-03-25 10:56

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="active",
        ),
        migrations.RemoveField(
            model_name="fullname",
            name="active",
        ),
        migrations.RemoveField(
            model_name="jobtitle",
            name="active",
        ),
        migrations.RemoveField(
            model_name="label",
            name="active",
        ),
        migrations.RemoveField(
            model_name="location",
            name="active",
        ),
        migrations.RemoveField(
            model_name="phone",
            name="active",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="active",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="active",
        ),
        migrations.AddField(
            model_name="label",
            name="skills",
            field=models.CharField(default="Skills", max_length=32),
        ),
        migrations.CreateModel(
            name="Active",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.BooleanField(default=True)),
                (
                    "profile",
                    auto_prefetch.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
