# Generated by Django 4.1.7 on 2023-04-02 15:50
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_skill_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activationsettings",
            old_name="skill_set",
            new_name="skill",
        ),
        migrations.RenameField(
            model_name="labelsettings",
            old_name="skill_set",
            new_name="skill",
        ),
    ]
