# Generated by Django 4.1.7 on 2023-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_remove_email_active_remove_fullname_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birth",
            name="active",
        ),
        migrations.RemoveField(
            model_name="description",
            name="active",
        ),
        migrations.RemoveField(
            model_name="description",
            name="label",
        ),
        migrations.RemoveField(
            model_name="website",
            name="active",
        ),
        migrations.AddField(
            model_name="active",
            name="skill",
            field=models.BooleanField(default=False),
        ),
    ]
