# Generated by Django 4.1.7 on 2023-06-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_alter_profile_jobtitle_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_active",
            field=models.BooleanField(default=True),
        ),
    ]
