# Generated by Django 4.1.7 on 2023-04-02 15:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_rename_skill_set_activationsettings_skill_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skillitem",
            old_name="set",
            new_name="skill",
        ),
        migrations.AlterField(
            model_name="activationsettings",
            name="skill",
            field=models.BooleanField(default=True),
        ),
    ]
