# Generated by Django 4.1.7 on 2023-03-25 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_skills_alter_skillitem_skill_delete_skill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skills",
            options={
                "base_manager_name": "prefetch_manager",
                "default_related_name": "skills",
            },
        ),
    ]
