# Generated by Django 4.1.7 on 2023-06-08 10:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_rename_description_profile_about_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TexProfile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profiles.profile",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
