# Generated by Django 4.1.7 on 2023-03-19 21:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_alter_profile_fullname_alter_profile_jobtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="label",
            field=models.CharField(default="About me", max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Date of birth"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Website"
            ),
        ),
    ]
