# Generated by Django 4.1.7 on 2023-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_alter_skill_options_remove_skill_text_skill_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
