# Generated by Django 4.1.7 on 2023-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_delete_texprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lang_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
