# Generated by Django 4.1.7 on 2023-03-25 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_rename_skills_skill_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "base_manager_name": "prefetch_manager",
                "default_related_name": "skill",
            },
        ),
    ]
