# Generated by Django 4.1.7 on 2023-04-08 08:42
import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_skill_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="profile",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
    ]
