# Generated by Django 4.1.7 on 2023-05-10 20:19
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_skill_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"base_manager_name": "prefetch_manager", "verbose_name": "Skills"},
        ),
    ]
