# Generated by Django 4.1.7 on 2023-06-09 10:44

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_key_setting_deepl_auth_key_and_more"),
        ("profiles", "0012_profile_lang_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="lang_code",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_lang",
            field=auto_prefetch.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
            ),
        ),
    ]
