# Generated by Django 4.1.7 on 2023-03-25 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_skill_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="active",
            old_name="skill_set",
            new_name="skill",
        ),
        migrations.RenameField(
            model_name="label",
            old_name="skill_set",
            new_name="skill",
        ),
    ]
