# Generated by Django 4.1.7 on 2023-03-25 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_rename_skill_set_active_skill_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Active",
            new_name="ActiveSetting",
        ),
        migrations.RenameModel(
            old_name="Label",
            new_name="LabelSetting",
        ),
    ]
