# Generated by Django 4.1.7 on 2023-05-14 19:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_alter_skill_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
