# Generated by Django 4.1.7 on 2023-06-09 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_remove_profile_lang_code_profile_profile_lang"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_lang",
            new_name="language_setting",
        ),
    ]
