# Generated by Django 4.1.7 on 2023-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_alter_skill_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ("order",),
                "verbose_name": "Skills",
            },
        ),
        migrations.RenameField(
            model_name="activationsettings",
            old_name="skill",
            new_name="skill_set",
        ),
    ]
