# Generated by Django 4.1.7 on 2023-06-09 11:11

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_key_setting_deepl_auth_key_and_more"),
        ("profiles", "0014_rename_profile_lang_profile_language_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language_setting",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
            ),
        ),
    ]
