# Generated by Django 4.1.7 on 2023-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_rename_active_activesetting_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_public", True)),
                fields=("slug",),
                name="profile_slug_unique_when_public",
            ),
        ),
    ]
