# Generated by Django 4.1.7 on 2023-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_alter_profile_options_profile_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
