# Generated by Django 4.1.7 on 2023-05-17 20:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labelsettings",
            old_name="skill",
            new_name="skill_set",
        ),
    ]
