# Generated by Django 4.1.7 on 2023-05-17 20:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_rename_skill_labelsettings_skill_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
