# Generated by Django 4.1.7 on 2023-03-25 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.RemoveConstraint(
            model_name="profile",
            name="profile_slug_unique_when_public",
        ),
    ]
