# Generated by Django 4.1.7 on 2023-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_public",
            new_name="public",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_temporary",
        ),
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.CharField(
                choices=[
                    ("temporal", "Temporal"),
                    ("user_profile", "User profile"),
                    ("template", "Template"),
                ],
                default="user_profile",
                max_length=16,
            ),
        ),
    ]
