# Generated by Django 4.1.7 on 2023-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_alter_skill_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="description",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Description",
            },
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="jobtitle",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="photo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="labelsettings",
            name="description",
            field=models.CharField(default="Description", max_length=32),
        ),
    ]
