# Generated by Django 4.1.7 on 2023-05-21 09:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_alter_description_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="rows",
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
