# Generated by Django 4.1.7 on 2023-03-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("profiles", "0018_rename_is_public_profile_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_set",
                to="sessions.session",
            ),
        ),
    ]
