# Generated by Django 4.1.7 on 2023-03-25 19:26

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("profiles", "0019_profile_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="session",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_set",
                to="sessions.session",
            ),
        ),
    ]
