# Generated by Django 4.1.7 on 2023-05-21 23:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_description_rows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="rows",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="photo",
            name="cropped",
            field=models.ImageField(null=True, upload_to="profiles/cropped-photos"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="full",
            field=models.ImageField(null=True, upload_to="profiles/full-photos"),
        ),
    ]
