# Generated by Django 4.1.7 on 2023-05-22 20:33

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0020_alter_description_rows_alter_photo_cropped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="cropped",
            field=models.ImageField(
                null=True, upload_to=apps.profiles.models.get_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="full",
            field=models.ImageField(
                null=True, upload_to=apps.profiles.models.get_upload_path
            ),
        ),
    ]
