# Generated by Django 4.1.7 on 2023-05-25 19:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0021_alter_photo_cropped_alter_photo_full"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.CharField(blank=True, max_length=50, null=True)),
                ("end_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
            ],
            options={
                "verbose_name": "Education",
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
