# Generated by Django 4.1.7 on 2023-05-25 19:40

import apps.profiles.models
import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0022_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="education",
            name="profile",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField(default=3)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            bases=(
                models.Model,
                apps.profiles.models.ProfileChildMixin,
                apps.profiles.models.LevelMethodsMixin,
            ),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
