# Generated by Django 4.1.7 on 2023-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0024_alter_education_options_alter_language_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationsettings",
            name="achievement_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="education_set",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="experience_set",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="language_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="project_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activationsettings",
            name="publication_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="achievement_set",
            field=models.CharField(default="Achievements", max_length=32),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="education_set",
            field=models.CharField(default="Education", max_length=32),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="experience_set",
            field=models.CharField(default="Work experience", max_length=32),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="language_set",
            field=models.CharField(default="Languages", max_length=32),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="project_set",
            field=models.CharField(default="Projects", max_length=32),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="publication_set",
            field=models.CharField(default="Publications", max_length=32),
        ),
    ]
