# Generated by Django 4.1.7 on 2023-05-26 17:03

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0025_activationsettings_achievement_set_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="inventors",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="issuer",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="number",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(
                verbose_name={"blank": True, "max_length": 1024, "null": True}
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="issuing_date",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="link",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="📝 Description"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🗓️ End"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="🏫 Institution"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🗓️ Start"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="🎓 Title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="profile",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="role",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
