# Generated by Django 4.1.7 on 2023-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0026_remove_achievement_inventors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="issuing_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="📝 Description"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🗓️ End"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🗓️ Start"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="🎓 Title"
            ),
        ),
    ]
