# Generated by Django 4.1.7 on 2023-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0027_rename_issuing_date_achievement_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="rows",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="experience",
            name="rows",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
