# Generated by Django 4.1.7 on 2023-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0028_education_rows_experience_rows"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="issuing_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="authors",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="date",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🗓️ Date"
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="🎓 Title"
            ),
        ),
    ]
