# Generated by Django 4.1.7 on 2023-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0029_rename_issuing_date_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="description",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Profile description",
            },
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="🏆 Goal achieved"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🏢 Company name"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="📍 Location"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="🧑\u200d💼 Job title"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.IntegerField(default=50, verbose_name="Level"),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=50, verbose_name="🗣️ Language"),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="🔗 Link"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="🤝anization"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="role",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="🧑\u200d💼 Role"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=34,
                null=True,
                verbose_name="🧑\u200d💼 Project name",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.IntegerField(default=50, verbose_name="Level"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, verbose_name="📊 Skill"),
        ),
    ]
