# Generated by Django 4.1.7 on 2023-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0030_alter_description_options_remove_achievement_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="description",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(max_length=64, verbose_name="🏆 Goal achieved"),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="📝 What did you learn?",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.CharField(max_length=16, verbose_name="🗓️ End date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=32, verbose_name="🏫 Institution"),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.CharField(max_length=16, verbose_name="🗓️ Start date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="title",
            field=models.CharField(max_length=64, verbose_name="🎓 Title"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(max_length=32, verbose_name="🏢 Company name"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="📝 What did you learn?",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.CharField(max_length=16, verbose_name="🗓️ End date"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(max_length=32, verbose_name="📍 Location"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.CharField(max_length=16, verbose_name="🗓️ Start date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="🤝 Organization"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="role",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="🧑\u200d💼 Role in the project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=64, verbose_name="🌍 Project name"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="date",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="🗓️ Date"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="link",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="🔗 Link"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="📑 Publisher"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=128, verbose_name="🔬 Publication title"),
        ),
    ]
