# Generated by Django 4.1.7 on 2023-06-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0031_remove_publication_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="text",
            field=models.EmailField(
                blank=True, max_length=32, null=True, verbose_name="📧Email"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="text",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="📞Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="text",
            field=models.URLField(default="as", max_length=32, verbose_name="🌐Website"),
            preserve_default=False,
        ),
    ]
