# Generated by Django 4.1.7 on 2023-06-04 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0032_alter_email_text_alter_phone_text_alter_website_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="website",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "🌐Website",
            },
        ),
    ]
