# Generated by Django 4.1.7 on 2023-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0033_alter_website_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phone",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "📞 Phone number",
            },
        ),
        migrations.AlterModelOptions(
            name="website",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Website",
            },
        ),
        migrations.AlterField(
            model_name="email",
            name="text",
            field=models.EmailField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="phone",
            name="text",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="text",
            field=models.URLField(max_length=32, verbose_name="Website"),
        ),
    ]
