# Generated by Django 4.1.7 on 2023-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0034_alter_phone_options_alter_website_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birth",
            name="text",
            field=models.CharField(default="adfadsf", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="description",
            name="text",
            field=models.TextField(verbose_name="Profile description"),
        ),
        migrations.AlterField(
            model_name="email",
            name="text",
            field=models.EmailField(default="asdsadf", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fullname",
            name="text",
            field=models.CharField(default="adfas", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="text",
            field=models.CharField(default="adsfasdf", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="text",
            field=models.CharField(default="adfasdf", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="phone",
            name="text",
            field=models.CharField(default="adsfadfa", max_length=16),
            preserve_default=False,
        ),
    ]
