# Generated by Django 4.1.7 on 2023-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0035_alter_birth_text_alter_description_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelsettings",
            name="description",
            field=models.CharField(default="About me", max_length=32),
        ),
    ]
