# Generated by Django 4.1.7 on 2023-06-04 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0036_alter_labelsettings_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="description",
            options={"base_manager_name": "prefetch_manager"},
        ),
    ]
