# Generated by Django 4.1.7 on 2023-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0037_alter_description_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fullname",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterField(
            model_name="fullname",
            name="text",
            field=models.CharField(max_length=32, verbose_name="Full name"),
        ),
    ]
