# Generated by Django 4.1.7 on 2023-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0039_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_photo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="label_website",
            field=models.CharField(default="Website", max_length=16),
        ),
    ]
