# Generated by Django 4.1.7 on 2023-03-11 12:56

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tex', '0002_alter_coverlettertemplate_options_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='honor',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('id', 'level')},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('-level',)},
        ),
        migrations.AlterModelOptions(
            name='volunteering',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('order', 'id')},
        ),
        migrations.AlterModelManagers(
            name='certification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='education',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='experience',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='honor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='language',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resume',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='skill',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='volunteering',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='certification',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tex.resumetemplate'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='profile',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteering_set', to='profiles.profile'),
        ),
    ]
