# Generated by Django 3.2.8 on 2021-12-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_label',
            field=models.CharField(default='Education', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_label',
            field=models.CharField(default='Experience', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='publication_label',
            field=models.CharField(default='Publications', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_label',
            field=models.CharField(default='Skills', max_length=100),
        ),
    ]
