# Generated by Django 4.0.3 on 2022-03-16 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texfiles', '0001_initial'),
        ('profiles', '0003_alter_certification_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='resumes/images')),
                ('pdf', models.FileField(null=True, upload_to='resumes/pdfs')),
            ],
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('id', 'level')},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-level',)},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='position_label',
            new_name='experience_label',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='maiden_name',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='volunteering',
            old_name='cause',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='role',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification_label',
            field=models.CharField(default='Certifications', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_label',
            field=models.CharField(default='Courses', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_label',
            field=models.CharField(default='About me', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_label',
            field=models.CharField(default='Honors and Awards', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobtitle_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_label',
            field=models.CharField(default='Languages', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_label',
            field=models.CharField(default='Organizations', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='patent_label',
            field=models.CharField(default='Patents', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stackoverflow',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stackoverflow_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteering_label',
            field=models.CharField(default='Volunteering work', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteering_set', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texfiles.resumetemplate'),
        ),
    ]
