# Generated by Django 3.2.8 on 2021-12-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20211225_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('inventors', models.CharField(blank=True, max_length=300, null=True)),
                ('application_number', models.IntegerField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('filling_date', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_modification',
        ),
        migrations.AddField(
            model_name='profile',
            name='imported_from_linkedin',
            field=models.BooleanField(default=False),
        ),
    ]
