# Generated by Django 3.2.8 on 2021-12-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20211226_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='summary',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='geo_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='imported_from_linkedin',
        ),
    ]
