# Generated by Django 3.2.8 on 2021-12-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20211227_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofilepicture',
            name='profile',
        ),
        migrations.DeleteModel(
            name='LinkedinBackgroundPicture',
        ),
        migrations.DeleteModel(
            name='LinkedinProfilePicture',
        ),
    ]
