# Generated by Django 3.2.8 on 2021-12-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20211227_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Linkedin', 'Linkedin'), ('Github', 'Github'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Other', 'Other')], max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_websites', to='profiles.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteeringinterest',
            name='profile',
        ),
        migrations.RenameField(
            model_name='volunteeringexperience',
            old_name='company_name',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='volunteeringexperience',
            old_name='linkedin_company',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='linkedin_data',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='linkedin_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='education',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='education',
            name='linkedin_data',
        ),
        migrations.RemoveField(
            model_name='education',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='education',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='education',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='honor',
            name='linkedin_data',
        ),
        migrations.RemoveField(
            model_name='honor',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='linkedin_company',
        ),
        migrations.RemoveField(
            model_name='position',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='volunteeringexperience',
            name='linkedin_id',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='LinkedinWebsite',
        ),
        migrations.DeleteModel(
            name='VolunteeringInterest',
        ),
    ]
