# Generated by Django 4.0 on 2021-12-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20211227_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='OrganizationMember',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_industry_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_last_modified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_vanity_name',
        ),
    ]
