# Generated by Django 4.0 on 2021-12-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_rename_organization_organizationmember_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='photo',
        ),
    ]
