# Generated by Django 4.0 on 2021-12-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rename_picture_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_full',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
