# Generated by Django 4.0 on 2022-01-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_photo_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Linkedin', 'Linkedin'), ('Github', 'Github'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Portfolio', 'Portfolio'), ('Other', 'Other')], max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/cropped_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_full',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/full_photos/'),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AddField(
            model_name='websitelink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_links', to='profiles.profile'),
        ),
    ]
