# Generated by Django 4.0 on 2022-01-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_profile_email_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitelink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='websitelink',
            name='label',
        ),
    ]
