# Generated by Django 4.0 on 2022-01-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_websitelink_category_remove_websitelink_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelink',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='globe', max_length=25, null=True),
        ),
    ]
