# Generated by Django 4.0 on 2022-01-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_websitelink_bootstrap_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bootstrap_icon', models.CharField(blank=True, default='globe', max_length=25, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='WebsiteLink',
        ),
    ]
