# Generated by Django 4.0 on 2022-01-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_website_delete_websitelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[('A1', 'A1. Very basic'), ('A2', 'A2. Basic'), ('B1', 'B1. Intermediate'), ('B2', 'B2. Advanced'), ('C1', 'C1. Very advanced'), ('Nt', 'Native')], default=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
        ),
    ]
