# Generated by Django 4.0 on 2022-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_skill_name_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(choices=[(0, 'Select Level'), (1, 'Very basic'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Very advanced'), (6, 'Native')], default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
