# Generated by Django 4.0 on 2022-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_language_level_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description_visible',
            field=models.IntegerField(default=True),
        ),
    ]
