# Generated by Django 4.0 on 2022-01-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_profile_description_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree_name',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='program',
            new_name='title',
        ),
    ]
