# Generated by Django 4.0 on 2022-01-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_rename_degree_name_education_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='profiles.profile'),
        ),
    ]
