# Generated by Django 4.0 on 2022-01-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_education_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school_name',
            new_name='institution',
        ),
    ]
