# Generated by Django 4.0 on 2022-01-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_rename_school_name_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
