# Generated by Django 4.0 on 2022-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_education_institution_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
