# Generated by Django 4.0 on 2022-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_alter_education_options_education_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_visible',
            field=models.BooleanField(default=True),
        ),
    ]
