# Generated by Django 4.0 on 2022-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_profile_education_visible_alter_education_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_visible',
            field=models.BooleanField(default=True),
        ),
    ]
