# Generated by Django 4.0 on 2022-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_experience_delete_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='location_name',
            new_name='company_link',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
