# Generated by Django 4.0 on 2022-01-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_rename_company_name_experience_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='job_title',
            new_name='title',
        ),
    ]
