# Generated by Django 4.0 on 2022-01-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_rename_job_title_experience_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution_link',
        ),
        migrations.RemoveField(
            model_name='education',
            name='order',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_visible',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_visible',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_visible',
            field=models.IntegerField(default=True),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='position',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='profiles.profile'),
        ),
    ]
