# Generated by Django 4.0 on 2022-01-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_position_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description_visible',
            new_name='description_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='education_active',
            field=models.IntegerField(default=True),
        ),
    ]
