# Generated by Django 4.0 on 2022-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_rename_description_visible_profile_description_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
