# Generated by Django 4.0.1 on 2022-01-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_experience_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('linkedin_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('cause', models.CharField(blank=True, max_length=100, null=True)),
                ('ongoing', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteeringexperience',
            name='profile',
        ),
        migrations.AddField(
            model_name='certification',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='honor',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patent',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='honors_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organizations_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='patents_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='publications_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteering_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='websites_active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
        migrations.DeleteModel(
            name='VolunteeringExperience',
        ),
        migrations.AddField(
            model_name='volunteering',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteering_experiences', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='profiles.profile'),
        ),
    ]
