# Generated by Django 4.1.2 on 2023-02-22 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texfiles', '0001_initial'),
        ('profiles', '0039_organization_volunteering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='resumes/images')),
                ('pdf', models.FileField(null=True, upload_to='resumes/pdfs')),
            ],
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='honor',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('id', 'level')},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-level',)},
        ),
        migrations.AlterModelOptions(
            name='volunteering',
            options={'ordering': ('order', 'id')},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='license',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='honor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='honor',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='honor',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='position',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='filling_date',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='linkedin_id',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certifications_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='honors_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='maiden_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organizations_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='patents_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position_label',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='publications_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='websites_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='role',
        ),
        migrations.AddField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuing_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='issuer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='issuing_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='honor',
            name='issuing_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='honor',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='issuing_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification_label',
            field=models.CharField(default='Certifications', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_label',
            field=models.CharField(default='Courses', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_label',
            field=models.CharField(default='About me', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_label',
            field=models.CharField(default='Work experience', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='honor_label',
            field=models.CharField(default='Honors and Awards', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobtitle_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_label',
            field=models.CharField(default='Languages', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_label',
            field=models.CharField(default='Organizations', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='patent_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='patent_label',
            field=models.CharField(default='Patents', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='publication_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stackoverflow',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stackoverflow_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteering_label',
            field=models.CharField(default='Volunteering work', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='issuing_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteering',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteering',
            name='organization_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_label',
            field=models.CharField(default='Projects', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='volunteering_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteering_set', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texfiles.resumetemplate'),
        ),
    ]
