# Generated by Django 4.1.7 on 2023-03-16 22:52
import django.db.models.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoverLetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("interpreter", models.CharField(default="lualatex", max_length=20)),
                ("image", models.ImageField(upload_to="tex/cover-letters/screenshots")),
                ("is_active", models.BooleanField(default=True)),
                ("credits", models.CharField(blank=True, max_length=128, null=True)),
                ("credits_url", models.URLField(blank=True, null=True)),
                ("downloads", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("template_name", models.CharField(default="test.tex", max_length=20)),
                ("only_one_page_allowed", models.BooleanField(default=False)),
                ("interpreter", models.CharField(default="lualatex", max_length=20)),
                ("image", models.ImageField(upload_to="tex-screenshots")),
                ("is_active", models.BooleanField(default=True)),
                ("credits", models.CharField(blank=True, max_length=50, null=True)),
                ("credits_url", models.URLField(blank=True, max_length=100, null=True)),
                ("downloads", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
