# Generated by Django 4.1.7 on 2023-06-11 08:11

from django.db import migrations, models
import django.db.models.manager
import slugger.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoverLetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("interpreter", models.CharField(default="lualatex", max_length=20)),
                ("image", models.ImageField(upload_to="tex/cover-letters/screenshots")),
                ("is_active", models.BooleanField(default=True)),
                ("credits", models.CharField(blank=True, max_length=128, null=True)),
                ("credits_url", models.URLField(blank=True, null=True)),
                ("downloads", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CvTex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("slug", slugger.fields.AutoSlugField(populate_from="title")),
                ("template_name", models.CharField(max_length=64, unique=True)),
                ("interpreter", models.CharField(default="lualatex", max_length=20)),
                ("image", models.ImageField(upload_to="tex-screenshots")),
                ("is_active", models.BooleanField(default=True)),
                ("license", models.CharField(max_length=32)),
                ("credits", models.CharField(blank=True, max_length=128, null=True)),
                ("credits_url", models.URLField(blank=True, max_length=128, null=True)),
                ("downloads", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
