# Generated by Django 4.1.7 on 2023-03-25 09:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_label"),
        ("tex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TexProfile",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "base_manager_name": "prefetch_manager",
                "indexes": [],
                "constraints": [],
            },
            bases=("profiles.profile",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
