# Generated by Django 4.1.7 on 2023-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumetemplate",
            name="template_name",
            field=models.CharField(default="test.tex", max_length=20, unique=True),
        ),
    ]
