# Generated by Django 4.1.7 on 2023-06-07 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0002_alter_resumetemplate_template_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResumeTemplate",
            new_name="Tex",
        ),
    ]
