# Generated by Django 4.1.7 on 2023-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0003_rename_resumetemplate_tex"),
    ]

    operations = [
        migrations.AddField(
            model_name="tex",
            name="is_cv",
            field=models.BooleanField(default=True),
        ),
    ]
