# Generated by Django 4.1.7 on 2023-06-08 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0005_cvtex_delete_tex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="texprofile",
            options={},
        ),
    ]
