# Generated by Django 4.1.7 on 2023-06-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0006_alter_texprofile_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvtex",
            name="name",
        ),
        migrations.RemoveField(
            model_name="cvtex",
            name="only_one_page_allowed",
        ),
        migrations.AddField(
            model_name="cvtex",
            name="license",
            field=models.CharField(default="MIT", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cvtex",
            name="title",
            field=models.CharField(default="hello", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="credits",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="credits_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="template_name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
