# Generated by Django 4.1.7 on 2023-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0007_remove_cvtex_name_remove_cvtex_only_one_page_allowed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvtex",
            name="credits",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
