# Generated by Django 4.1.7 on 2023-06-09 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0008_alter_cvtex_credits"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TexProfile",
        ),
    ]
