# Generated by Django 4.1.7 on 2023-06-09 07:22

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0009_delete_texprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtex",
            name="slug",
            field=slugger.fields.AutoSlugField(default="aasdf", populate_from="title"),
            preserve_default=False,
        ),
    ]
