# Generated by Django 4.1.7 on 2023-03-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpremiumplan",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userpremiumplan",
            name="expires",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userpremiumplan",
            name="starts",
            field=models.DateField(),
        ),
    ]
