# Generated by Django 4.1.7 on 2023-03-17 21:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_userpremiumplan_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notify_when_plan_expires",
            field=models.BooleanField(default=False),
        ),
    ]
