# Generated by Django 4.1.7 on 2023-03-18 00:19
import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_notify_when_plan_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpremiumplan",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="premium_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
