[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py311']

[tool.isort]
profile = "black"
add_imports = "from __future__ import annotations"
