# Generated by Django 4.1.7 on 2023-06-11 22:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TexProxyProfile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.profile",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="language",
            name="name_de",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="name_en",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="name_es",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
    ]
