# Generated by Django 4.2.2 on 2023-08-02 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanFAQ",
        ),
    ]
