# Generated by Django 4.2.2 on 2023-06-23 05:22
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_credits_url_tex_source_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freeplan",
            options={"base_manager_name": "prefetch_manager"},
        ),
    ]
