# Generated by Django 4.1.7 on 2023-06-14 19:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_cvtex_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvtex",
            name="license",
            field=models.CharField(
                default="MIT",
                editable=False,
                help_text="Read from metadata",
                max_length=32,
            ),
        ),
    ]
