# Generated by Django 4.1.7 on 2023-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_texproxyprofile_language_name_de_language_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfaq",
            name="answer_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="answer_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="question_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="question_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="question_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="description_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="description_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="description_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="name_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="name_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="name_es",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
