# Generated by Django 4.1.7 on 2023-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_cvtex_interpreter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
