# Generated by Django 4.2.2 on 2023-08-14 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_premiumplan_description_de_premiumplan_name_de"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="notify_when_plan_expires",
        ),
    ]
