# Generated by Django 4.2.2 on 2023-06-23 05:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_freeplan_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="secrets",
            name="plans_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secrets",
            name="profiles_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secrets",
            name="user_dashboard_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
