# Generated by Django 4.1.7 on 2023-06-14 19:27

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_cvtex_license"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvtex",
            old_name="is_active",
            new_name="active",
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="slug",
            field=slugger.fields.AutoSlugField(
                editable=False,
                help_text="Calculated from title field",
                populate_from="title",
            ),
        ),
    ]
