# Generated by Django 4.1.7 on 2023-06-22 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_cv_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cv",
            old_name="text",
            new_name="rendered_text",
        ),
    ]
