# Generated by Django 4.1.7 on 2023-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_planfaq_answer_de_planfaq_answer_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="rendering_time",
            field=models.FloatField(null=True),
        ),
    ]
