# Generated by Django 4.2.2 on 2023-06-23 05:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_secrets_plans_url_secrets_profiles_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secrets",
            name="plans_url",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="secrets",
            name="profiles_url",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="secrets",
            name="user_dashboard_url",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
