# Generated by Django 4.1.7 on 2023-06-16 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_is_active_cvtex_active_alter_cvtex_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TexProxyLanguage",
        ),
        migrations.DeleteModel(
            name="TexProxyProfile",
        ),
    ]
