# Generated by Django 4.1.7 on 2023-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_cv_rendering_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="image_rendering_time",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="pdf_rendering_time",
            field=models.FloatField(null=True),
        ),
    ]
