# Generated by Django 4.1.7 on 2023-06-22 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_text_cv_rendered_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CvTex",
            new_name="Tex",
        ),
    ]
