# Generated by Django 4.2.2 on 2023-06-27 20:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_secrets_plans_url_alter_secrets_profiles_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tex",
            name="source_url",
            field=models.URLField(
                editable=False,
                help_text="Read from metadata",
                max_length=255,
                null=True,
            ),
        ),
    ]
