# Generated by Django 4.1.7 on 2023-06-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_cvtex_tex"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="auto_created",
            field=models.BooleanField(default=False),
        ),
    ]
