# Generated by Django 4.2.2 on 2023-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_tex_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tex",
            name="interpreter",
            field=models.CharField(
                default="xelatex",
                editable=False,
                help_text="Read from metadata",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="tex",
            name="license",
            field=models.CharField(
                default="MIT",
                editable=False,
                help_text="Read from metadata",
                max_length=64,
            ),
        ),
    ]
