# Generated by Django 4.1.7 on 2023-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_cv_image_rendering_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvtex",
            name="image",
        ),
        migrations.AddField(
            model_name="language",
            name="name_fr",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="answer_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="question_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="description_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="name_fr",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="interpreter",
            field=models.CharField(default="lualatex", max_length=32),
        ),
    ]
