# Generated by Django 4.2.2 on 2023-06-30 03:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_tex_interpreter_alter_tex_license"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteUrls",
            fields=[
                (
                    "singleton",
                    models.BooleanField(
                        default=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "profiles_url",
                    models.URLField(blank=True, editable=False, null=True),
                ),
                ("plans_url", models.URLField(blank=True, editable=False, null=True)),
                (
                    "user_dashboard_url",
                    models.URLField(blank=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="secrets",
            name="single_setting_model",
        ),
        migrations.RemoveField(
            model_name="secrets",
            name="plans_url",
        ),
        migrations.RemoveField(
            model_name="secrets",
            name="profiles_url",
        ),
        migrations.RemoveField(
            model_name="secrets",
            name="user_dashboard_url",
        ),
        migrations.AddConstraint(
            model_name="secrets",
            constraint=models.CheckConstraint(
                check=models.Q(("singleton", True)), name="single_secrets_model"
            ),
        ),
        migrations.AddConstraint(
            model_name="siteurls",
            constraint=models.CheckConstraint(
                check=models.Q(("singleton", True)), name="single_siteurls_model"
            ),
        ),
    ]
