# Generated by Django 4.1.7 on 2023-06-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_cvtex_image_language_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="rendering_time",
            field=models.FloatField(default=0),
        ),
    ]
