# Generated by Django 4.1.7 on 2023-06-13 04:47

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_cv_rendering_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvtex",
            name="credits",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Read from metadata",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="credits_url",
            field=models.URLField(
                blank=True,
                editable=False,
                help_text="Read from metadata",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="interpreter",
            field=models.CharField(
                default="lualatex",
                editable=False,
                help_text="Read from metadata",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="license",
            field=models.CharField(
                editable=False, help_text="Read from metadata", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="slug",
            field=slugger.fields.AutoSlugField(
                editable=False, help_text="Read from metadata", populate_from="title"
            ),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="template_name",
            field=models.CharField(
                editable=False,
                help_text="Read from metadata",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cvtex",
            name="title",
            field=models.CharField(
                editable=False, help_text="Read from metadata", max_length=64
            ),
        ),
    ]
