# Generated by Django 4.2.2 on 2023-06-30 19:41
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_siteurls_remove_secrets_single_setting_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="language",
            name="name_es",
        ),
        migrations.RemoveField(
            model_name="language",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="planfaq",
            name="answer_de",
        ),
        migrations.RemoveField(
            model_name="planfaq",
            name="answer_es",
        ),
        migrations.RemoveField(
            model_name="planfaq",
            name="answer_fr",
        ),
        migrations.RemoveField(
            model_name="planfaq",
            name="question_de",
        ),
        migrations.RemoveField(
            model_name="planfaq",
            name="question_es",
        ),
        migrations.RemoveField(
            model_name="planfaq",
            name="question_fr",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="name_es",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="name_fr",
        ),
    ]
