# Generated by Django 4.1.7 on 2023-06-13 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_cvtex_credits_alter_cvtex_credits_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="use_in_faker",
        ),
    ]
