# Generated by Django 4.2.2 on 2023-07-01 11:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_deepllanguage_remove_profile_lang_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteUrls",
        ),
    ]
