# Generated by Django 4.2.2 on 2023-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_delete_siteurls"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfaq",
            name="answer_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="planfaq",
            name="question_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="description_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="name_es",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
