# Generated by Django 4.2.5 on 2023-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_delete_secrets_alter_cv_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freeplan",
            old_name="support",
            new_name="includes_support",
        ),
        migrations.RenameField(
            model_name="premiumplan",
            old_name="support",
            new_name="includes_support",
        ),
        migrations.RemoveField(
            model_name="freeplan",
            name="cvs_per_profile",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="cvs_per_profile",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(max_length=65, verbose_name="🏆 Goal achieved"),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="📝 Description"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=33, verbose_name="🏫 Institution"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(max_length=33, verbose_name="🏢 Company name"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="📝 Description"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(max_length=33, verbose_name="📍 Location"),
        ),
        migrations.AlterField(
            model_name="freeplan",
            name="description",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="freeplan",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="description",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="description_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="description_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="description_es",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
