# Generated by Django 4.2.5 on 2023-12-25 10:38

import core.models.profiles
import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_support_freeplan_includes_support_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tex",
            name="is_premium",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cropped_photo",
            field=models.ImageField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PurePosixPath("/home/rami/nicecv/media"),
                ),
                upload_to=core.models.profiles.get_photo_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="tex",
            name="credits",
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tex",
            name="interpreter",
            field=models.CharField(default="xelatex", editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name="tex",
            name="interpreter_options",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="tex",
            name="license",
            field=models.CharField(default="MIT", editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="tex",
            name="source_url",
            field=models.URLField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tex",
            name="title",
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
