# Generated by Django 4.2.5 on 2023-12-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_tex_is_premium_alter_profile_cropped_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tex",
            name="is_premium",
            field=models.BooleanField(default=True),
        ),
    ]
