# Generated by Django 4.2.5 on 2023-12-25 16:50

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_tex_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeplan",
            name="premium_templates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="premium_templates",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="category",
            field=models.CharField(
                choices=[
                    ("temporal", "⏳ Temporal"),
                    ("user", "👤 User profile"),
                    ("template", "📊 Template"),
                ],
                default="user",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="userpremiumplan",
            name="plan",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.premiumplan",
            ),
        ),
    ]
