# Generated by Django 4.2.5 on 2023-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_freeplan_premium_templates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=32, verbose_name="🏫 Institution"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(max_length=32, verbose_name="🏢 Company name"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(max_length=32, verbose_name="📍 Location"),
        ),
    ]
