# Generated by Django 4.2.5 on 2023-12-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_freeplan_profile_manual_premiumplan_profile_manual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumplan",
            name="premium_templates",
            field=models.BooleanField(default=False),
        ),
    ]
