# Generated by Django 4.2.5 on 2024-01-01 20:37

import auto_prefetch
from django.db import migrations
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0012_2_8"),
        ("core", "0020_alter_premiumplan_premium_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpremiumplan",
            name="customer",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.customer",
            ),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                default="EUR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
