# Generated by Django 4.2.5 on 2024-01-01 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_userpremiumplan_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpremiumplan",
            name="customer",
        ),
    ]
