# Generated by Django 4.2.5 on 2024-01-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_userpremiumplan_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="asked_to_verify_email",
            field=models.BooleanField(default=False),
        ),
    ]
