# Generated by Django 4.2.5 on 2024-01-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
