# Generated by Django 4.2.5 on 2024-01-04 22:38

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumplan",
            name="price_max",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("50"),
                default_currency="EUR",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="price_max_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                default="EUR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="price_min",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("5"),
                default_currency="EUR",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="price_min_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                default="EUR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
