# Generated by Django 4.2.5 on 2024-01-05 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_premiumplan_price_max_premiumplan_price_max_currency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="premiumplan",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ("months", "price_min"),
            },
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="price",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="price_currency",
        ),
    ]
