# Generated by Django 4.2.5 on 2024-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_premiumplan_options_remove_premiumplan_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeplan",
            name="name_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="freeplan",
            name="name_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="freeplan",
            name="name_es",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
