# Generated by Django 4.2.5 on 2024-01-05 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_freeplan_name_de_freeplan_name_en_freeplan_name_es"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="gdp",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50000"), max_digits=12
            ),
        ),
    ]
