# Generated by Django 4.2.5 on 2024-01-05 16:54

import core.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_country_gdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cropped_photo",
            field=models.ImageField(
                null=True, upload_to=core.models.profiles.get_photo_upload_path
            ),
        ),
    ]
