# Generated by Django 4.1.2 on 2022-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField()),
                ('default', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saving', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stripe_product_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('months', 'price'),
            },
        ),
    ]
