# Generated by Django 4.1.7 on 2023-03-11 13:54
import django.db.models.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_alter_order_options_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=16)),
                ("question_en", models.CharField(max_length=16, null=True)),
                ("question_es", models.CharField(max_length=16, null=True)),
                ("question_de", models.CharField(max_length=16, null=True)),
                ("question_fr", models.CharField(max_length=16, null=True)),
                ("question_pt", models.CharField(max_length=16, null=True)),
                ("question_it", models.CharField(max_length=16, null=True)),
                ("answer", models.TextField()),
                ("answer_en", models.TextField(null=True)),
                ("answer_es", models.TextField(null=True)),
                ("answer_de", models.TextField(null=True)),
                ("answer_fr", models.TextField(null=True)),
                ("answer_pt", models.TextField(null=True)),
                ("answer_it", models.TextField(null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="name",
            field=models.CharField(default="Plan", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="name_de",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_en",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_es",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_fr",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_it",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_pt",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
