# Generated by Django 4.1.7 on 2023-03-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_plan_price_currency_alter_plan_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="max_profiles",
            new_name="profiles",
        ),
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
