# Generated by Django 4.1.7 on 2023-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0006_rename_max_profiles_plan_profiles_plan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="coverletters",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
