# Generated by Django 4.1.7 on 2023-03-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0007_plan_coverletters"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_es",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
