# Generated by Django 4.1.7 on 2023-03-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0008_plan_description_de_plan_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="support",
            field=models.BooleanField(default=True),
        ),
    ]
