# Generated by Django 4.1.7 on 2023-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0009_plan_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfaq",
            name="question",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="planfaq",
            name="question_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="planfaq",
            name="question_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="planfaq",
            name="question_es",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
