# Generated by Django 4.1.7 on 2023-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_actual_plan_customuser_plan"),
        ("plans", "0010_alter_planfaq_question_alter_planfaq_question_de_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plan",
            new_name="PremiumPlan",
        ),
    ]
