# Generated by Django 4.2.2 on 2023-07-30 20:33

import cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmenus.models.menuitems
import wagtailmenus.models.menus
import wagtailmenus.models.mixins
import wagtailsvg.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CustomFlatMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="For internal reference only.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "handle",
                    models.SlugField(
                        help_text="Used to reference this menu in templates etc. Must be unique for the selected site.",
                        max_length=100,
                        verbose_name="handle",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="If supplied, appears above the menu when rendered.",
                        max_length=255,
                        verbose_name="heading",
                    ),
                ),
                (
                    "heading_en",
                    models.CharField(
                        blank=True,
                        help_text="If supplied, appears above the menu when rendered.",
                        max_length=255,
                        null=True,
                        verbose_name="heading",
                    ),
                ),
                (
                    "heading_es",
                    models.CharField(
                        blank=True,
                        help_text="If supplied, appears above the menu when rendered.",
                        max_length=255,
                        null=True,
                        verbose_name="heading",
                    ),
                ),
                (
                    "max_levels",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1: No sub-navigation (flat)"),
                            (2, "2: Allow 1 level of sub-navigation"),
                            (3, "3: Allow 2 levels of sub-navigation"),
                            (4, "4: Allow 3 levels of sub-navigation"),
                        ],
                        default=1,
                        help_text="The maximum number of levels to display when rendering this menu. The value can be overidden by supplying a different <code>max_levels</code> value to the <code>{% flat_menu %}</code> tag in your templates.",
                        verbose_name="maximum levels",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "flat menu",
                "verbose_name_plural": "flat menus",
                "abstract": False,
                "unique_together": {("site", "handle")},
            },
            bases=(
                wagtailmenus.models.mixins.DefinesSubMenuTemplatesMixin,
                models.Model,
                wagtailmenus.models.menus.Menu,
            ),
        ),
        migrations.CreateModel(
            name="CustomMainMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_levels",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1: No sub-navigation (flat)"),
                            (2, "2: Allow 1 level of sub-navigation"),
                            (3, "3: Allow 2 levels of sub-navigation"),
                            (4, "4: Allow 3 levels of sub-navigation"),
                        ],
                        default=2,
                        help_text="The maximum number of levels to display when rendering this menu. The value can be overidden by supplying a different <code>max_levels</code> value to the <code>{% main_menu %}</code> tag in your templates.",
                        verbose_name="maximum levels",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "main menu",
                "verbose_name_plural": "main menu",
                "abstract": False,
            },
            bases=(
                wagtailmenus.models.mixins.DefinesSubMenuTemplatesMixin,
                models.Model,
                wagtailmenus.models.menus.Menu,
            ),
        ),
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hero_section_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "template_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "with-phone-mockup",
                                                        "With phone mockup",
                                                    ),
                                                    (
                                                        "split-with-image",
                                                        "Split with image",
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "hero_title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Write a title",
                                                max_length=255,
                                                null=True,
                                            ),
                                        ),
                                        (
                                            "hero_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Write an introduction",
                                                max_length=255,
                                                null=True,
                                            ),
                                        ),
                                        (
                                            "hero_cta",
                                            wagtail.blocks.CharBlock(
                                                help_text="Text to display on Call to Action",
                                                max_length=255,
                                                null=True,
                                                verbose_name="Hero CTA",
                                            ),
                                        ),
                                        (
                                            "hero_cta_link",
                                            wagtail.blocks.PageChooserBlock(),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "header_section_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading_text",
                                            wagtail.blocks.CharBlock(
                                                form_classname="title", required=True
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "template_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("simple", "Simple"),
                                                    (
                                                        "simple-on-dark",
                                                        "Simple on dark",
                                                    ),
                                                    ("centered", "Centered"),
                                                    (
                                                        "centered-on-dark",
                                                        "Centered on dark",
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "feature_section_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Write the heading",
                                                max_length=255,
                                                null=True,
                                            ),
                                        ),
                                        (
                                            "slogan",
                                            wagtail.blocks.CharBlock(
                                                help_text="Add a slogan",
                                                max_length=255,
                                                null=True,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.TextBlock(
                                                help_text="Description of the feature section",
                                                max_length=512,
                                                null=True,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "template_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("centered", "Centered"),
                                                    ("with-offset", "With offset"),
                                                    (
                                                        "with-image-on-left",
                                                        "With image on left",
                                                    ),
                                                    (
                                                        "with-image-on-right",
                                                        "With image on right",
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "name",
                                                            wagtail.blocks.CharBlock(
                                                                blank=True,
                                                                help_text="Feature name",
                                                                max_length=255,
                                                                null=True,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                blank=True,
                                                                help_text="Feature description",
                                                                max_length=512,
                                                                null=True,
                                                            ),
                                                        ),
                                                        (
                                                            "svg",
                                                            wagtailsvg.blocks.SvgChooserBlock(
                                                                help_text="Feature svg"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                label="Feature items",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("embed_section_block", cms.blocks.EmbedSectionBlock()),
                            (
                                "rich_text_section_block",
                                cms.blocks.RichTextSection(),
                            ),
                            (
                                "quote_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("text", wagtail.blocks.TextBlock()),
                                        (
                                            "attribute_name",
                                            wagtail.blocks.CharBlock(
                                                blank=True,
                                                label="e.g. Mary Berry",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="Home content block",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PureDjangoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TextPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text_section_block",
                                cms.blocks.RichTextSection(
                                    features=[
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="Home content block",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SocialMediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="Facebook URL", null=True),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Twitter URL", null=True),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True, help_text="YouTube Channel URL", null=True
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="Linkedin URL", null=True),
                ),
                (
                    "github",
                    models.URLField(blank=True, help_text="GitHub URL", null=True),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Instagram URL", null=True),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterSlogan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("text_en", models.TextField(blank=True, null=True)),
                ("text_es", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomMainMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="link to a custom URL",
                    ),
                ),
                (
                    "url_append",
                    models.CharField(
                        blank=True,
                        help_text="Use this to optionally append a #hash or querystring to the above page's URL.",
                        max_length=255,
                        verbose_name="append to URL",
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        help_text="Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.",
                        max_length=100,
                        verbose_name="handle",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                        max_length=255,
                        verbose_name="link text",
                    ),
                ),
                (
                    "link_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                        max_length=255,
                        null=True,
                        verbose_name="link text",
                    ),
                ),
                (
                    "link_text_es",
                    models.CharField(
                        blank=True,
                        help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                        max_length=255,
                        null=True,
                        verbose_name="link text",
                    ),
                ),
                (
                    "allow_subnav",
                    models.BooleanField(
                        default=True,
                        help_text="NOTE: The sub-menu might not be displayed, even if checked. It depends on how the menu is used in this project's templates.",
                        verbose_name="allow sub-menu for this item",
                    ),
                ),
                ("add_to_profile_dropdown", models.BooleanField(default=False)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.page",
                        verbose_name="link to an internal page",
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="cms.custommainmenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
                "ordering": ("sort_order",),
                "abstract": False,
            },
            bases=(models.Model, wagtailmenus.models.menuitems.MenuItem),
        ),
        migrations.CreateModel(
            name="CustomFlatMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="link to a custom URL",
                    ),
                ),
                (
                    "url_append",
                    models.CharField(
                        blank=True,
                        help_text="Use this to optionally append a #hash or querystring to the above page's URL.",
                        max_length=255,
                        verbose_name="append to URL",
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        help_text="Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.",
                        max_length=100,
                        verbose_name="handle",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                        max_length=255,
                        verbose_name="link text",
                    ),
                ),
                (
                    "link_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                        max_length=255,
                        null=True,
                        verbose_name="link text",
                    ),
                ),
                (
                    "link_text_es",
                    models.CharField(
                        blank=True,
                        help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                        max_length=255,
                        null=True,
                        verbose_name="link text",
                    ),
                ),
                (
                    "allow_subnav",
                    models.BooleanField(
                        default=False,
                        help_text="NOTE: The sub-menu might not be displayed, even if checked. It depends on how the menu is used in this project's templates.",
                        verbose_name="allow sub-menu for this item",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.page",
                        verbose_name="link to an internal page",
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="cms.customflatmenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
                "ordering": ("sort_order",),
                "abstract": False,
            },
            bases=(models.Model, wagtailmenus.models.menuitems.MenuItem),
        ),
    ]
