# Generated by Django 4.2.2 on 2023-06-30 19:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteUrls",
            fields=[
                (
                    "singleton",
                    models.BooleanField(
                        default=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "profiles_url",
                    models.URLField(blank=True, editable=False, null=True),
                ),
                ("plans_url", models.URLField(blank=True, editable=False, null=True)),
                (
                    "user_dashboard_url",
                    models.URLField(blank=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="siteurls",
            constraint=models.CheckConstraint(
                check=models.Q(("singleton", True)), name="single_siteurls_model"
            ),
        ),
    ]
