# Generated by Django 4.2.2 on 2023-06-30 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_siteurls_siteurls_single_siteurls_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteUrls",
        ),
    ]
