# Generated by Django 4.2.5 on 2024-01-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_legal"),
    ]

    operations = [
        migrations.AddField(
            model_name="legal",
            name="impress_page_de",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="impress_page_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="impress_page_es",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="privacy_policy_page_de",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="privacy_policy_page_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="privacy_policy_page_es",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="terms_page_de",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="terms_page_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
        migrations.AddField(
            model_name="legal",
            name="terms_page_es",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.textpage",
            ),
        ),
    ]
