# Generated by Django 4.2.2 on 2023-07-31 20:17
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("cms", "0003_alter_blogpost_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="BlogPostPage",
        ),
        migrations.RenameModel(
            old_name="PureDjangoPage",
            new_name="DjangoServedPage",
        ),
    ]
