# Generated by Django 4.2.2 on 2023-07-01 07:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_corepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="corepage",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
