# Generated by Django 4.2.5 on 2024-01-07 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_legal_impress_page_de_legal_impress_page_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customflatmenuitem",
            name="link_page",
        ),
        migrations.RemoveField(
            model_name="customflatmenuitem",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="custommainmenu",
            name="site",
        ),
        migrations.RemoveField(
            model_name="custommainmenuitem",
            name="link_page",
        ),
        migrations.RemoveField(
            model_name="custommainmenuitem",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="footer_text_de",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="footer_text_en",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="footer_text_es",
        ),
        migrations.DeleteModel(
            name="CustomFlatMenu",
        ),
        migrations.DeleteModel(
            name="CustomFlatMenuItem",
        ),
        migrations.DeleteModel(
            name="CustomMainMenu",
        ),
        migrations.DeleteModel(
            name="CustomMainMenuItem",
        ),
    ]
