# Generated by Django 4.2.2 on 2023-07-01 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_corepage_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corepage",
            name="link",
        ),
    ]
