# Generated by Django 4.2.5 on 2024-01-07 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_remove_customflatmenuitem_link_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="footer_text",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="svg_footer",
        ),
    ]
