# Generated by Django 4.2.2 on 2023-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_custommainmenuitem_add_to_profile_dropdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="customflatmenu",
            name="heading_en",
            field=models.CharField(
                blank=True,
                help_text="If supplied, appears above the menu when rendered.",
                max_length=255,
                null=True,
                verbose_name="heading",
            ),
        ),
        migrations.AddField(
            model_name="customflatmenu",
            name="heading_es",
            field=models.CharField(
                blank=True,
                help_text="If supplied, appears above the menu when rendered.",
                max_length=255,
                null=True,
                verbose_name="heading",
            ),
        ),
    ]
