# Generated by Django 4.2.2 on 2023-07-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("cms", "0007_customflatmenu_heading_en_customflatmenu_heading_es"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="Facebook URL", null=True),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Twitter URL", null=True),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True, help_text="YouTube Channel URL", null=True
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="Linkedin URL", null=True),
                ),
                (
                    "github",
                    models.URLField(blank=True, help_text="GitHub URL", null=True),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="GitHub URL", null=True),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterSlogan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=50, null=True)),
                ("text_en", models.CharField(blank=True, max_length=50, null=True)),
                ("text_es", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
