# Generated by Django 4.2.2 on 2023-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_socialmedialinks_footerslogan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerslogan",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="footerslogan",
            name="text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="footerslogan",
            name="text_es",
            field=models.TextField(blank=True, null=True),
        ),
    ]
