# Generated by Django 4.2.2 on 2023-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_alter_footerslogan_text_alter_footerslogan_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialinks",
            name="linkedin_en",
            field=models.URLField(blank=True, help_text="Linkedin URL", null=True),
        ),
        migrations.AddField(
            model_name="socialmedialinks",
            name="linkedin_es",
            field=models.URLField(blank=True, help_text="Linkedin URL", null=True),
        ),
    ]
