# Generated by Django 4.2.2 on 2023-07-02 20:49
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_rootpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RootPage",
        ),
    ]
