# Generated by Django 4.2.2 on 2023-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("cms", "0010_socialmedialinks_linkedin_en_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CorePage",
            new_name="PureDjangoPage",
        ),
        migrations.RemoveField(
            model_name="socialmedialinks",
            name="linkedin_en",
        ),
        migrations.RemoveField(
            model_name="socialmedialinks",
            name="linkedin_es",
        ),
        migrations.AlterField(
            model_name="socialmedialinks",
            name="instagram",
            field=models.URLField(blank=True, help_text="Instagram URL", null=True),
        ),
    ]
