# Generated by Django 4.2.2 on 2023-08-01 19:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_alter_banner_page_alter_banner_page_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
