# Generated by Django 4.2.2 on 2023-07-07 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_localizedmainmenu_localizedmainmenuitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localizedmainmenuitem",
            name="link_page",
        ),
        migrations.RemoveField(
            model_name="localizedmainmenuitem",
            name="menu",
        ),
        migrations.DeleteModel(
            name="LocalizedMainMenu",
        ),
        migrations.DeleteModel(
            name="LocalizedMainMenuItem",
        ),
    ]
