# Generated by Django 4.2.2 on 2023-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_banner_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="title",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
