# Generated by Django 4.2.2 on 2023-08-01 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0014_banner_title_en_banner_title_es"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="page",
            new_name="linked_page",
        ),
        migrations.RenameField(
            model_name="banner",
            old_name="page_en",
            new_name="linked_page_en",
        ),
        migrations.RenameField(
            model_name="banner",
            old_name="page_es",
            new_name="linked_page_es",
        ),
    ]
