# Generated by Django 4.2.2 on 2023-08-05 21:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0023_person_blogpersonrelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="description",
            field=models.TextField(default="Dummy description", max_length=1024),
            preserve_default=False,
        ),
    ]
