# Generated by Django 4.2.2 on 2023-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0025_brand_delete_footerslogan"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="name",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
