# Generated by Django 4.2.5 on 2023-09-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cms", "0027_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="svg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
