# Generated by Django 4.1.7 on 2023-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Setting",
            new_name="Settings",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="available_in_deepl",
            new_name="is_source_in_deepl",
        ),
        migrations.RemoveField(
            model_name="language",
            name="deepl_formality",
        ),
        migrations.AddField(
            model_name="language",
            name="is_target_in_deepl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="language",
            name="supports_formality",
            field=models.BooleanField(
                default=False, verbose_name="Supports formality in Deepl"
            ),
        ),
    ]
