# Generated by Django 4.1.7 on 2023-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="has_formality",
            field=models.BooleanField(
                default=False, verbose_name="Support formality on Deepl"
            ),
        ),
    ]
