# Generated by Django 4.1.7 on 2023-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_setting_settings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="use_in_faker",
            field=models.BooleanField(default=False),
        ),
    ]
