# Generated by Django 4.1.7 on 2023-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_language_use_in_faker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="supports_formality",
        ),
        migrations.AddField(
            model_name="language",
            name="supports_formality_in_deepl",
            field=models.BooleanField(default=False),
        ),
    ]
