# Generated by Django 4.1.7 on 2023-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_language_has_formality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="has_formality",
            new_name="deepl_formality",
        ),
        migrations.AddField(
            model_name="language",
            name="available_in_deepl",
            field=models.BooleanField(default=False),
        ),
    ]
