# Generated by Django 4.1.7 on 2023-06-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_has_formality_language_deepl_formality_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "singleton",
                    models.BooleanField(
                        default=True, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255)),
                ("value", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.CheckConstraint(
                check=models.Q(("singleton", True)), name="single_setting_model"
            ),
        ),
    ]
