# Generated by Django 4.1.7 on 2023-06-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_language_supports_formality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="name_de",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="name_en",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="name_es",
            field=models.CharField(default="Other Language", max_length=32, null=True),
        ),
    ]
