# Generated by Django 4.1.7 on 2023-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_setting_delete_settings_setting_single_setting_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="key",
            new_name="deepl_auth_key",
        ),
        migrations.RenameField(
            model_name="setting",
            old_name="value",
            new_name="facebook_app_id",
        ),
        migrations.AddField(
            model_name="setting",
            name="facebook_app_secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="facebook_page_access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="facebook_page_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="instagram_access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="instagram_page_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_client_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_organization_access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_organization_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_organization_refresh_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="linkedin_profile_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="name",
            field=models.CharField(
                default="API keys and dynamic settings", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_access_token_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_api_key_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_bearer_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_client_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="setting",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
