# Generated by Django 4.1.7 on 2023-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_key_setting_deepl_auth_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(default="Other Language", max_length=32),
        ),
    ]
