# Generated by Django 3.2.8 on 2021-11-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
