# Generated by Django 3.2.8 on 2021-11-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_paid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAdopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
