# Generated by Django 4.1.7 on 2023-03-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='actual_plan',
            new_name='plan',
        ),
    ]
