# Generated by Django 4.0 on 2021-12-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarlyAdopter',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
