# Generated by Django 4.0 on 2021-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
