# Generated by Django 4.0 on 2021-12-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_has_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_paid',
        ),
    ]
