# Generated by Django 4.2.2 on 2023-07-31 20:10
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import cms.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("embed_section_block", cms.blocks.EmbedSectionBlock()),
                    ("rich_text_section_block", cms.blocks.RichTextSection()),
                    (
                        "quote_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Mary Berry",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Home content block",
            ),
        ),
    ]
