# Generated by Django 4.2.2 on 2023-08-03 19:48
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0019_categorypage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryPage",
        ),
    ]
