# Generated by Django 4.2.2 on 2023-08-05 09:28
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("cms", "0021_alter_blogpostpage_body_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="linked_page_de",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="text_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_de",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="customflatmenu",
            name="heading_de",
            field=models.CharField(
                blank=True,
                help_text="If supplied, appears above the menu when rendered.",
                max_length=255,
                null=True,
                verbose_name="heading",
            ),
        ),
        migrations.AddField(
            model_name="customflatmenuitem",
            name="link_text_de",
            field=models.CharField(
                blank=True,
                help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                max_length=255,
                null=True,
                verbose_name="link text",
            ),
        ),
        migrations.AddField(
            model_name="custommainmenuitem",
            name="link_text_de",
            field=models.CharField(
                blank=True,
                help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.",
                max_length=255,
                null=True,
                verbose_name="link text",
            ),
        ),
        migrations.AddField(
            model_name="footerslogan",
            name="text_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frequentaskedquestion",
            name="answer_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="frequentaskedquestion",
            name="question_de",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
