# Generated by Django 4.0.3 on 2022-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='only_one_page_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
