# Generated by Django 4.1.2 on 2022-11-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverlettertemplate',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='coverlettertemplate',
            name='file',
        ),
    ]
