# Generated by Django 4.0.3 on 2022-04-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0002_resumetemplate_only_one_page_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverlettertemplate',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='coverlettertemplate',
            name='file',
        ),
    ]
