# Generated by Django 4.1.2 on 2022-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0002_remove_coverlettertemplate_cls_and_more'),
        ('texfiles', '0003_remove_coverlettertemplate_cls_and_more'),
    ]

    operations = [
    ]
