# Generated by Django 4.1.7 on 2023-03-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeplan",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="name_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="name_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="premiumplan",
            name="name_es",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
