# Generated by Django 4.1.7 on 2023-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeplan",
            name="name",
            field=models.CharField(default="Free Plan", max_length=32),
        ),
    ]
