# Generated by Django 4.1.7 on 2023-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="freeplan",
            name="single_free_plan",
        ),
        migrations.RenameField(
            model_name="freeplan",
            old_name="the_singleton",
            new_name="singleton",
        ),
        migrations.RemoveField(
            model_name="freeplan",
            name="coverletters",
        ),
        migrations.RemoveField(
            model_name="premiumplan",
            name="coverletters",
        ),
        migrations.AddField(
            model_name="freeplan",
            name="profile_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="premiumplan",
            name="profile_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="freeplan",
            constraint=models.CheckConstraint(
                check=models.Q(("singleton", True)), name="single_free_plan"
            ),
        ),
    ]
