# Generated by Django 4.1.7 on 2023-06-10 15:30

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tex", "0001_initial"),
        ("cvs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="tex",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="tex.cvtex"
            ),
        ),
    ]
