# Generated by Django 4.1.7 on 2023-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="image",
            field=models.ImageField(default="adsads", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="pdf",
            field=models.FileField(default="adfa", upload_to=""),
            preserve_default=False,
        ),
    ]
