# Generated by Django 4.1.7 on 2023-06-10 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0002_alter_cv_tex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="lang_code",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="language",
        ),
    ]
