# Generated by Django 4.1.7 on 2023-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0002_cv_image_cv_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
