# Generated by Django 4.1.7 on 2023-06-10 18:44

import apps.cvs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0003_remove_cv_lang_code_remove_cv_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="image",
            field=models.ImageField(upload_to=apps.cvs.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name="cv",
            name="pdf",
            field=models.FileField(upload_to=apps.cvs.models.get_upload_path),
        ),
    ]
