# Generated by Django 4.1.7 on 2023-06-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0003_cv_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="lang_code",
            field=models.CharField(default="en", max_length=5),
            preserve_default=False,
        ),
    ]
