# Generated by Django 4.1.7 on 2023-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0004_cv_lang_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="lang_code",
            field=models.CharField(default="en", max_length=5),
        ),
    ]
