# Generated by Django 4.1.7 on 2023-06-09 11:22

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_language_name"),
        ("cvs", "0005_alter_cv_lang_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="language",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
            ),
        ),
    ]
